include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Riskkit
Riskkit_FILES = $(wildcard *.xm)
Riskkit_FRAMEWORKS = UIKit
Riskkit_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/tweak.mk
include $(THEOS)/makefiles/aggregate.mk